name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to jFrog
        uses: docker/login-action@v2
        with:
          registry: http://13.231.139.12:8081/artifactory.jfrog.io
          username: ${{ secrets.JFROGUSERNAME }}
          password: ${{ secrets.JFROGPASSWORD }}
      -
        name: push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: http://13.231.139.12:8081/artifactory/libs-snapshot-local.jfrog.io/abc123119/test:latest
