name: Push Docker Image to JFrog

on:
  workflow_dispatch:

jobs:
  pushToJFrog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          jfrog-cli-version: 'latest'
          
      - name: Log in to JFrog Container Registry
        env:
          DOCKER_USERNAME: ${{ secrets.JFROG_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          DOCKER_REGISTRY: http://13.231.139.12:8081
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY

      - name: Build and Push JAR file
        env:
          JFROG_REPO: docker-repos
          JAR_FILE_PATH: target/lenovo.war
        run: |
          jfrog rt u "${JAR_FILE_PATH}" "${JFROG_REPO}/<TARGET_PATH>
