
name: Push Docker Image to JFrog

on:
  workflow_dispatch:

jobs:
  pushToJFrog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          jfrog-cli-version: 'latest'
          
      - name: Setup JFrog cli
        uses: jfrog/setup-jfrog-cli@v3
        env:
         JF_URL: http://13.231.139.12:8081
         username : ${{ secrets.JFROGUSERNAME }}
         password : ${{ secrets.JFROGPASSWORD }}
         
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest
   
          
      
