name: Push Docker Image to JFrog

on:
  workflow_dispatch:

jobs:
  pushToJFrog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with:
          jfrog-cli-version: 'latest'

      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t jfro-img:${IMAGE_TAG} .
          docker tag jfro-img:${IMAGE_TAG}
          docker login -u ${{ secrets.JFROGUSERNAME }} -p ${{ secrets.JFROGPASSWORD }} http://13.231.139.12:8081
          docker push jfro-img:${IMAGE_TAG}
