name: Push Docker Image to JFrog

on:
  workflow_dispatch:

jobs:
  pushToJFrog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          jfrog-cli-version: 'latest'
          
      - name: Build and Push Docker Image
        env:
         IMAGE_TAG: ${{ github.sha }}
         JFROG_REGISTRY: 13.231.139.12:8081
         REPO: docker-repos
         IMAGE_NAME: dock-img
        run: |
         docker build -t fro-img:${IMAGE_TAG} .
         docker tag fro-img:${IMAGE_TAG} ${JFROG_REGISTRY}/${REPO}/${IMAGE_NAME}:${IMAGE_TAG}
         docker login -u ${{ secrets.JFROG_USERNAME }} -p ${{ secrets.JFROG_PASSWORD }} ${JFROG_REGISTRY}
         docker push ${JFROG_REGISTRY}/${REPO}/${IMAGE_NAME}:${IMAGE_TAG}
