
name: Push Docker Image to JFrog

on:
  workflow_dispatch:

jobs:
  pushToJFrog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          jfrog-cli-version: 'latest'
          
      - name: Setup JFrog cli
        uses: jfrog/setup-jfrog-cli@v3
        env:
         JF_URL: http://13.231.139.12:8081
         username : ${{ secrets.JFROGUSERNAME }}
         password : ${{ secrets.JFROGPASSWORD }}
   
      - name: Build and Push Docker Image
        env:
         IMAGE_TAG: ${{ github.sha }}
         JFROG_REGISTRY: 13.231.139.12:8081
         REPO: docker-repos
         IMAGE_NAME: dock-img
        run : | 
            docker build -t fro-img:${IMAGE_TAG} .
            docker images
            docker info
      
      - name: Inspect Docker image
        run: docker inspect fro-img:${{ github.sha }}
        id: inspect
        
      - name: Display image location
        run: |
           echo "Image location:${{ steps.inspect.outputs.stdout }}"  
           sudo chmod -R 777 /var/lib/docker/overlay2
           jf rt u "/usr/local/tomcat" "http://13.231.139.12:8081/docker-repos/"    
      
